pipeline:

  build:
    image: golang:1.10
    commands:
      - go get github.com/uswitch/loglet/cmd/loglet
      - cp $GOPATH/bin/loglet ./loglet

  s3-branch:
    image: plugins/s3
    secrets: [ AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY ]
    acl: public-read
    region: "eu-west-1"
    bucket: "uswitch-public-tools"
    source: ./loglet
    target: loglet/${DRONE_BRANCH}/${DRONE_BUILD_NUMBER}/loglet

  s3-tag:
    when:
      event: tag
    image: plugins/s3
    secrets: [ AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY ]
    acl: public-read
    region: "eu-west-1"
    bucket: "uswitch-public-tools"
    source: ./loglet
    target: loglet/tagged/${DRONE_TAG}/loglet

  s3-latest:
    when:
      event: tag
    image: plugins/s3
    secrets: [ AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY ]
    acl: public-read
    region: "eu-west-1"
    bucket: "uswitch-public-tools"
    source: ./loglet
    target: loglet/latest/loglet
