sudo: false
language: go
go:
  - 1.11.x
script:
  - make test
after_success:
  - make release
  - for tgz in $(git ls-files -o | grep tar.gz); do echo $tgz $(openssl sha256 < $tgz); done
branches:
  only:
    - master
addons:
  artifacts:
    paths:
      - '$(git ls-files -o | grep .tar.gz | tr "\n" ":")'
    debug: true
    s3_region: eu-west-1
    s3_bucket: remerge-artifacts
    target_paths: $TRAVIS_REPO_SLUG
